### ISSUE TITLE
Websocket issue after upgrade to v1.2.39

### ISSUE THREAD

**Issue by ebouaziz** [YunoHost-Apps/uptime-kuma_ynh#92]
### Describe the bug

After upgrade, the webUI complains that it cannot establish websocket connection.

### Context

- Hardware: PC at home
- YunoHost version: 11.2.7
- I have access to my server: Through SSH & through the webadmin & direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: upgrading from  to 1.2.39
- If upgrading, current package version: 1.2.38

### Steps to reproduce

   1. Upgrade to 1.2.39
   2. Connect to webUI
   3. Observe Red banner stating websocket won't connect

### Logs

Sorry no logs

**Comment by ebouaziz** [comment]
Same issue after a clean install, the service status is `active (running)` and nothing significant shows in the logs.

**Comment by CodeShakingSheep** [comment]
Same here
![image](https://github.com/YunoHost-Apps/uptime-kuma_ynh/assets/19874562/deb4020a-910d-42c9-a151-8a716420653c)

**Comment by ketsapiwiq** [comment]
Hi @CodeShakingSheep, @ebouaziz,
Can you test again with the new version? Normally the fix has been merged.

**Comment by ebouaziz** [comment]
Hi @ketsapiwiq , I confirm that v1.2.40 fixed the issue.

**Comment by CodeShakingSheep** [comment]
Hi @ketsapiwiq ,
I just did a fresh install of UptimeKuma (as I still can't restore my old instance due to https://github.com/YunoHost-Apps/uptime-kuma_ynh/issues/93 ) With the new version this issue is fixed. Thank you.
